name: Frontend Analyze (manual)

on:
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Build analyze report
        working-directory: frontend
        run: npm run analyze

      - name: Upload analyze report
        uses: actions/upload-artifact@v4
        with:
          name: frontend-bundle-stats
          path: frontend/dist/stats.html

name: Frontend Bundle Analyze

on:
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Build with analyzer
        run: npm run analyze

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: bundle-report
          path: frontend/dist/stats.html
          if-no-files-found: error


