name: Smoke - Health Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker compose up backend deps
        run: |
          docker compose up -d postgres redis
          sleep 5

      - name: Build and start backend
        working-directory: backend
        env:
          NODE_ENV: production
          PORT: 3001
          DATABASE_URL: postgres://user:password@localhost:5433/ainvestfeed
        run: |
          npm ci
          npm run build
          nohup node dist/server.js > api.log 2>&1 &
          for i in {1..30}; do curl -sSf http://localhost:3001/health && break || sleep 1; done

      - name: Print health
        run: curl -sS http://localhost:3001/health | tee health.json

      - name: Upload backend logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: api-log
          path: backend/api.log


